#!/bin/sh

COMMIT_MSG_FILE="$1"

if grep -q "^Change-Id: I[0-9a-f]\{40\}$" "$COMMIT_MSG_FILE"; then
    exit 0
fi

CHANGE_ID="I$(echo $(date +%s%N) | sha1sum | cut -c1-40)"

if ! tail -n 5 "$COMMIT_MSG_FILE" | grep -q "^Change-Id: I[0-9a-f]\{40\}$"; then
    {
        echo ""
        echo "Change-Id: $CHANGE_ID"
    } >> "$COMMIT_MSG_FILE"
fi
